#!/usr/bin/env php
<?php

require __DIR__.'/src/bootstrap.php';

use Symfony\Component\Console\Application;
use Codeigniter\Installer\Command;

$app = new Symfony\Component\Console\Application('Codeigniter Installer','1.0.0');
$command = new Codeigniter\Installer\Command();
$app->add($command);
$app->run();

