#!/usr/bin/env php
<?php
require __DIR__.'/src/bootstrap.php';

use Symfony\Component\Console\Application;
use Codeigniter\Installer\Command;

/**
 * Codeigniter Global Installer
 *
 * @author     David Sosa Valdes <https://github.com/davidsosavaldes>
 * @license    MIT License
 * @link       https://github.com/davidsosavaldes/Codeigniter-Installer
 * @copyright  Copyright (c) 2016, David Sosa Valdes.
 */

$app = new Symfony\Component\Console\Application('Codeigniter Installer', '1.1.6');
$command = new Codeigniter\Installer\Command();
$app->add($command);
$app->run();